### ISSUE TITLE
Compilation error with ghc 7.4 installing 0.4.1.1 with cabal

### ISSUE THREAD

**Issue by rrthomas** [kfish/hogg#1]
I get the following error:

Downloading hogg-0.4.1.1...
Configuring hogg-0.4.1.1...
Building hogg-0.4.1.1...
Preprocessing library hogg-0.4.1.1...
[ 1 of 20] Compiling Codec.Container.Ogg.Dump ( Codec/Container/Ogg/Dump.hs, dist/build/Codec/Container/Ogg/Dump.o )
[ 2 of 20] Compiling Codec.Container.Ogg.CRC ( Codec/Container/Ogg/CRC.hs, dist/build/Codec/Container/Ogg/CRC.o )
[ 3 of 20] Compiling Codec.Container.Ogg.TimeScheme ( Codec/Container/Ogg/TimeScheme.hs, dist/build/Codec/Container/Ogg/TimeScheme.o )
[ 4 of 20] Compiling Codec.Container.Ogg.MessageHeaders ( Codec/Container/Ogg/MessageHeaders.hs, dist/build/Codec/Container/Ogg/MessageHeaders.o )
[ 5 of 20] Compiling Codec.Container.Ogg.Granulerate ( Codec/Container/Ogg/Granulerate.hs, dist/build/Codec/Container/Ogg/Granulerate.o )
[ 6 of 20] Compiling Codec.Container.Ogg.ByteFields ( Codec/Container/Ogg/ByteFields.hs, dist/build/Codec/Container/Ogg/ByteFields.o )
[ 7 of 20] Compiling Codec.Container.Ogg.RawPage ( Codec/Container/Ogg/RawPage.hs, dist/build/Codec/Container/Ogg/RawPage.o )
[ 8 of 20] Compiling Codec.Container.Ogg.Timestamp ( Codec/Container/Ogg/Timestamp.hs, dist/build/Codec/Container/Ogg/Timestamp.o )
[ 9 of 20] Compiling Codec.Container.Ogg.List ( Codec/Container/Ogg/List.hs, dist/build/Codec/Container/Ogg/List.o )
[10 of 20] Compiling Codec.Container.Ogg.Serial ( Codec/Container/Ogg/Serial.hs, dist/build/Codec/Container/Ogg/Serial.o )

Codec/Container/Ogg/Serial.hs:48:10:
    Duplicate instance declarations:
      instance Random Serial
        -- Defined at Codec/Container/Ogg/Serial.hs:48:10
      instance Random Word32 -- Defined in `System.Random'
cabal: Error: some packages failed to install:
hogg-0.4.1.1 failed during the building phase. The exception was:
ExitFailure 1

Using ghc 7.4.1 as shipped with Ubuntu 12.04.

**Comment by kfish** [comment]
Fixed in b0e46a7

**Comment by kfish** [comment]
Also, hogg-0.4.1.2 is now on hackage with this fix, so "cabal install hogg" should work.

**Comment by rrthomas** [comment]
Thanks very much for the quick fix!
